name: Build and Release
on:
    push:
        tags:
            - "*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Build
              id: build
              run: |
                  npm install
                  npm run build
            - name: Set tag variable
              id: set-tag-var
              run: |
                  echo "::set-output name=tag::$(git describe --abbrev=0) --tags"
            # Create the release on github
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
                with:
                  tag_name: ${{ github.ref }}
                  files: |
                    main.js
                    manifest.json
                    styles.css